id: PF1B6E664
initial_creation_type: ocr
source_metadata:
  volumes:
    5f00979240614c65873c4a98cd1d0bc1:
      base_file: v012.txt
      image_group_id: I1PD95857
      title: རིགས་ལྡན་མའི་དེ་ཁོ་ན་ཉིད་ངེས་པ།
      total_pages: 1544
      volume_number: 12
