id: PF1B6E664
initial_creation_type: ocr
source_metadata:
  volumes:
    a64adf60b8ef491e82eb6d5cc635ac59:
      base_file: v012.txt
      image_group_id: I1PD95857
      title: རིགས་ལྡན་མའི་དེ་ཁོ་ན་ཉིད་ངེས་པ།
      total_pages: 1544
      volume_number: 12
